//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signbook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signbook.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراءة الكود.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص كفيف.
        /// </summary>
        public static string Blind {
            get {
                return ResourceManager.GetString("Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الدولة.
        /// </summary>
        public static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع الإعاقة.
        /// </summary>
        public static string ChangeDisabilityType {
            get {
                return ResourceManager.GetString("ChangeDisabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر الدولة.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع الإعاقة.
        /// </summary>
        public static string ChooseDisabilityType {
            get {
                return ResourceManager.GetString("ChooseDisabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص أصم.
        /// </summary>
        public static string Deaf {
            get {
                return ResourceManager.GetString("Deaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصر.
        /// </summary>
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبار عالمية.
        /// </summary>
        public static string InternationalNews {
            get {
                return ResourceManager.GetString("InternationalNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأردن.
        /// </summary>
        public static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري التحميل.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبار محلية.
        /// </summary>
        public static string LocalNews {
            get {
                return ResourceManager.GetString("LocalNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الرسالة.
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنبيهات.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمان.
        /// </summary>
        public static string Omman {
            get {
                return ResourceManager.GetString("Omman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تفعيل إشعارات التطبيق من الإعدادات.
        /// </summary>
        public static string PleaseEnableNotificationFromSetting {
            get {
                return ResourceManager.GetString("PleaseEnableNotificationFromSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نفذ.
        /// </summary>
        public static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاقتراحات.
        /// </summary>
        public static string SuggestionAndComplition {
            get {
                return ResourceManager.GetString("SuggestionAndComplition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلانات.
        /// </summary>
        public static string ThirdNews {
            get {
                return ResourceManager.GetString("ThirdNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيديو.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
