//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signbook.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Signbook.Resources.AppResource.ar", typeof(AppResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        public static string Blind {
            get {
                return ResourceManager.GetString("Blind", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        public static string ChangeDisabilityType {
            get {
                return ResourceManager.GetString("ChangeDisabilityType", resourceCulture);
            }
        }
        
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        public static string ChooseDisabilityType {
            get {
                return ResourceManager.GetString("ChooseDisabilityType", resourceCulture);
            }
        }
        
        public static string Deaf {
            get {
                return ResourceManager.GetString("Deaf", resourceCulture);
            }
        }
        
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string InternationalNews {
            get {
                return ResourceManager.GetString("InternationalNews", resourceCulture);
            }
        }
        
        public static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LocalNews {
            get {
                return ResourceManager.GetString("LocalNews", resourceCulture);
            }
        }
        
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string Omman {
            get {
                return ResourceManager.GetString("Omman", resourceCulture);
            }
        }
        
        public static string PleaseEnableNotificationFromSetting {
            get {
                return ResourceManager.GetString("PleaseEnableNotificationFromSetting", resourceCulture);
            }
        }
        
        public static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string SuggestionAndComplition {
            get {
                return ResourceManager.GetString("SuggestionAndComplition", resourceCulture);
            }
        }
        
        public static string ThirdNews {
            get {
                return ResourceManager.GetString("ThirdNews", resourceCulture);
            }
        }
    }
}
